services:
  # Dotnet Backend Service
  web_dotnet:
    container_name: web_dotnet
    build:
      context: ./.devcontainer/backend/
      dockerfile: ./Dockerfile-Backend
    command: dotnet watch run --project ./TheOmniLifeCoreApi

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - ./.env

    volumes:
      - web_dotnet:/p-nut-TheOmniLifeCoreApi
      
    networks:
      - app
      - db

    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
        reservations:
          cpus: 1
          memory: 2G


  # Angular Frontend Service
  web_angular:
    container_name: web_angular
    build:
      context: ./.devcontainer/frontend/
      dockerfile: ./Dockerfile-Frontend
    command: npm start
    
    volumes:
      - web_angular:/p-nut-theomnilife-frontend

    networks:
      - app

    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2G
  
  
  # Nginx Reverse Proxy Service
  reverse-proxy:
    image: caddy:latest
    container_name: reverse-proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"

    networks: 
      - app
      - db
      
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M


  # MySQL Database Service
  db:
    image: mysql:latest
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app
      - db

    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 512M


  # Django Automation Service
  django_automation:
    container_name: django_automation
    build:
      context: ./.devcontainer/automation/
      dockerfile: ./Dockerfile-Automation
    command: python reportgen/manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    
    volumes:
      - django_automation:/pnut-reportautomationbackend
      - python_packages:/usr/local/lib/python3.12/site-packages/

    networks:
      - app
      - db

    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2G


  # Appsmith Service
  appsmith:
    image: appsmith/appsmith-ce:latest
    container_name: appsmith
    volumes:
      - appsmith:/appsmith-stacks

    networks:
      - app
      - db

    deploy:
      resources:
        limits:
          cpus: 1.5
          memory: 3G

volumes:
  db:
  appsmith:
  web_dotnet:
  web_angular:
  django_automation:
  python_packages:
  nginx_logs:


networks:
  app:
    driver: bridge

  db:
    driver: bridge